import mongoose, { Model, ObjectId, Schema } from "mongoose";
import { AppTimeStamp } from "./time-stamp";
import crypto from "crypto";

export interface IApiKey {
  keyId: string;
  userId: string;
  keyHash: string; // Hashed API key for security
  name?: string; // Optional name/description for the key
  lastUsedAt?: Date;
  expiresAt?: Date;
  isActive: boolean;
}

export interface IApiKeyDocument extends IApiKey, Document, AppTimeStamp {
  _id: ObjectId;
  id: string;
  verifyKey(key: string): boolean;
}

export interface IApiKeyModel extends Model<IApiKeyDocument> {
  hashKey(key: string): string;
  generateKey(): string;
}

const ApiKeySchema = new Schema<IApiKeyDocument>(
  {
    _id: {
      type: mongoose.Schema.Types.ObjectId,
      required: true,
      auto: true,
    },
    keyId: {
      type: String,
      unique: true,
      // Will be auto-populated in pre-save hook from _id
    },
    userId: {
      type: String,
      required: true,
      index: true,
    },
    keyHash: {
      type: String,
      required: true,
      index: true,
    },
    name: {
      type: String,
      default: '',
    },
    lastUsedAt: {
      type: Date,
    },
    expiresAt: {
      type: Date,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  {
    timestamps: true,
  }
);

// Automatically convert `_id` to `id`
ApiKeySchema.set('toJSON', {
  virtuals: true,
  versionKey: false,
  transform: (_, ret: any) => {
    ret.id = ret._id.toString();
    delete ret._id;
  }
});

ApiKeySchema.pre('save', async function () {
  const doc = this;
  // Always set keyId from _id (similar to Project model's projectId)
  // _id is auto-generated by Mongoose before pre-save hook runs
  doc.keyId = doc._id.toString();
});

// Static method to hash API key
ApiKeySchema.statics.hashKey = function (key: string): string {
  return crypto.createHash('sha256').update(key).digest('hex');
};

// Instance method to verify API key
ApiKeySchema.methods.verifyKey = function (key: string): boolean {
  const hash = crypto.createHash('sha256').update(key).digest('hex');
  return hash === this.keyHash;
};

// Static method to generate a new API key
ApiKeySchema.statics.generateKey = function (): string {
  // Generate a secure random API key
  // Format: tms_<random-base64-string>
  const randomBytes = crypto.randomBytes(32);
  const base64Key = randomBytes.toString('base64url');
  return `tms_${base64Key}`;
};

export const ApiKey: Model<IApiKeyDocument> = mongoose.models?.ApiKey || mongoose.model<IApiKeyDocument, IApiKeyModel>('ApiKey', ApiKeySchema);
